### PR TITLE
mix of eta <--> beta ?

### PR DESCRIPTION
**Pull request by aviadlevis**

### CODE REVIEW

**Comment by achael** [comment]
I think this should be beta, not eta. This is trying to make the number of equatorial crossings continuous across the horizontal beta=0 axis of the image. It's related to the heaviside function in eq 82 here https://arxiv.org/pdf/1910.12873.pdf

**Comment by aviadlevis** [comment]
When this is set to `beta` you get a lack of symmetry with respect to above or below the equator. Using the code below with `beta=-5` or `beta=5` produces the following figures where the top figure has `maxwarps=3` and the bottom has `maxwarps=2`
beta=-5_maxwraps=3
beta=5_maxwraps=2


```
beta = 5
npix = 64
ngeo = 200
inclination = np.pi/2
distance = 1000.0
spin = 1e-6
image_coords = [np.linspace(-8.0,8.0,npix), beta * np.ones(npix)]
observer_coords=[0, distance, inclination, 0]

geos = kgeo.raytrace_ana(spin, observer_coords, image_coords, ngeo)
```

**Comment by achael** [comment]
I think there are 2 things going on here, both related to the inclination being high (close to 90 degrees)

One is that the definition of nmax_eq really is not symmetric above and below beta=0 for close to edge on. As the inclination increases to 90 degrees, the 'n=1' region expands to take up more and more of the lower half image plane. Here it is at 60 degrees: 

image

At exactly edge on, the n=1 region will fill the entire  lower half image plane will be nmax_eq=1.  This is because most of the upper half image plane is looking at the 'top' side of the equatorial plane and the bottom half plane is looking at the 'bottom' side of the equatorial plane. 

But when I was looking into this i also saw some weird behavior in the nmax_eq quantity for beta<0 at high inclination -- here in this figure at 85 degrees you can see some oscillation between 0 and 1, which i think is wrong -- i will look into this

image

 
`import kerr_raytracing_ana as kgeo
import matplotlib.pyplot as plt

inclination = 85.*np.pi/180. 

beta = 5
npix = 256 
ngeo = 200 
distance = 1000.0 
spin = 1.e-6

image_coords = [np.linspace(-20.0,20.0,npix), beta * np.ones(npix)] 
observer_coords=[0, distance, inclination, 0]   
geos = kgeo.raytrace_ana(spin, observer_coords, image_coords, ngeo,plotdata=False) 
alpha1 = geos.alpha; nmax1 = geos.nmax_eq;

image_coords = [np.linspace(-20.0,20.0,npix), -beta * np.ones(npix)] 
observer_coords=[0, distance, inclination, 0]   
geos = kgeo.raytrace_ana(spin, observer_coords, image_coords, ngeo,plotdata=False) 
alpha2 = geos.alpha; nmax2 = geos.nmax_eq;

plt.figure()
plt.plot(alpha1,nmax1,'k-', label='beta = 3')
plt.plot(alpha2,nmax2,'r--', label='beta = -3')
plt.xlabel('alpha')
plt.ylabel('nmax')
plt.legend()
plt.show()`

**Comment by achael** [comment]
the edge artifacts in the above plot seem to go away as i increase rmax -- this makes some sense as the equations for nmax i think only actually hold in the rmax->infinity limit, but i am giving them a mino time tau the endpoint of the geodesic that is actually at a finite (large) distance. I'll look into this more. 
image

```python
import kerr_raytracing_ana as kgeo
import matplotlib.pyplot as plt
import numpy as np

inclination = 85.*np.pi/180. 

beta = 5
npix = 256 
ngeo = 200
distance = 1000000.0 
spin = 1.e-6

image_coords = [np.linspace(-20.0,20.0,npix), beta * np.ones(npix)] 
observer_coords=[0, distance, inclination, 0]   
geos = kgeo.raytrace_ana(spin, observer_coords, image_coords, ngeo,plotdata=False) 
alpha1 = geos.alpha; nmax1 = geos.nmax_eq;

image_coords = [np.linspace(-20.0,20.0,npix), -beta * np.ones(npix)] 
observer_coords=[0, distance, inclination, 0]   
geos = kgeo.raytrace_ana(spin, observer_coords, image_coords, ngeo,plotdata=False) 
alpha2 = geos.alpha; nmax2 = geos.nmax_eq;

plt.figure()
plt.plot(alpha1,nmax1,'k-', label='beta = %i'%beta)
plt.plot(alpha2,nmax2,'r--', label='beta = -%i'%beta)
plt.xlabel('alpha')
plt.ylabel('nmax')
plt.legend()
plt.show()
```

anyway, in summary I think the coloring in the plots you showed is correct based on the quantity nmax that they are being colored by, but we might want to choose something else to label the geodesics by. There is a quantity geos.n_poloidal that may be better....

**Comment by achael** [comment]
I added a new option 'n_label' to geos.plotgeos. if you set n_label='poloidal', it will label/color the curves by the number of poloidal orbits instead of the number of equatorial crossings, and this looks symmetric for +/- beta in the example you sent. Try: 

```python
import matplotlib.pyplot as plt
import numpy as np
import kerr_raytracing_ana as kgeo

beta = 5
npix = 64
ngeo = 200
inclination = np.pi/2
distance = 100000.0
spin = 1e-6
image_coords = [np.linspace(-8.0,8.0,npix), beta * np.ones(npix)]
observer_coords=[0, distance, inclination, 0]

geos = kgeo.raytrace_ana(spin, observer_coords, image_coords, ngeo,plotdata=False)
geos.plotgeos(n_label='poloidal')
```

**Pull request closed without merging**
